@startuml
actor "user" as user
node "Kotlin Restful" {
    component "controller" as controller
    component "service" as service
    component "repository" as repository

}
database "PostgreSQL" as database

user <--> controller
controller <--> service
service <--> repository
repository <--> database

@enduml